language: python
before_install:
    - sudo apt-get install python-pip python-virtualenv
install:
    - virtualenv venv
    - source venv/bin/activate
    - pip install numpy
    - pip install nose
    - python setup.py build
script: bash continuous_integration/travis_test.sh
